baseURL = "https://jhayes.github.io/"
title = "Jack Hayes' Blog"
languageCode = "en-us"
#theme = "hyde"
theme = "hello-friend-ng"
paginate = 10

[params]
  author = "Jack Hayes"
  description = "A blog."