#+hugo_base_dir: ./
#+hugo_section: posts
#+hugo_auto_set_lastmod: t
#+date: [2024-06-28 Fri]
#+lastmod: [2024-06-28 Fri]
#+title: Emacs modifications
#+hugo_tags: emacs

* Summary
This is a list of some niggles and how I deal with them as a reference.

* Deleting the first ‘x’ characters from every line in a region with Emacs.
You use your mark tool (‘C-Spc’) to highlight a box area and then use the command ‘C-x r k’ to remove this square/rectangle.

Don’t worry about the mark tool highlighting the edges of lines in between, they won’t be clipped.

[[https://stackoverflow.com/questions/15929872/deleting-the-first-x-characters-from-every-line-in-a-region-with-emacs][Link]]
* Handy way to append a flag to the end of a line.
Command: M-< M-x replace-regexp RET $ RET a RET

This will place an ‘a’ at the end of all lines. The $ matches the end-of-line character.

Also one of the other answers shows how to use key-macros so could be handy later.
* Reload configurations without restarting Emacs
A quick way to reload your .emacs after making changes, to save a restart.

// M-x eval-buffer

[[https://stackoverflow.com/questions/167705/reload-configurations-without-restarting-emacs][Link]]
* Finding location of .emacs file.
C-h v 'user-init-file'

[[https://stackoverflow.com/questions/864892/how-do-i-find-which-emacs-file-has-been-loaded][Link]]
