#+hugo_base_dir: ./
#+hugo_section: posts
#+hugo_auto_set_lastmod: t
#+hugo_draft: false

#+title: Venting
#+hugo_tags: house

* Summary 
Clickbait title, couldn't resist the obvious one! This page is just a collection of details on the vents in my house for future Jack.

* Vents (Exhaust Units)

Exhaust units are the devices that pull air out of a room, also called vents.
There are three vents in the house. These are located in the kitchen, downstairs toilet and upstairs bathroom.

They all look similar but are actually different variants, all designed by Aereco.
There is a comparison table located [[https://www.aereco.ie/products/exhaust-units-ie/bxc-2/#characteristics][here]].

Just in case it disappears later, the gist of it is:
- The bathroom ones have a boost feature when a person is present.
- The kitchen and bathroom check for humidity (I guess the thinking is that a downstairs toilet won't have much water vapour anyways).
- The kitchen one needs to be reset after the powerdown event.
- The kitchen one's presence sensor lights up green, unlike the others (as a way of communicating diagnostics, whereas the sensor is used in the other variants and doesn't light up).

| Location          | Type      | Part Number | Humidity Sensitive | Boost Airflow | Boost Airflow based on presence detection |
| Kitchen           | BXC^2 hps | BXC1898     | Y                  | N             | N                                         |
| Upstairs Bathroom | BXC^2 hpd | BXC1908     | Y                  | Y             | Y                                         |
| Downstairs Toilet | BXC^2 pd  | BXC1905     | N                  | Y             | Y                                         |

- Troubleshooting guide for the [[file:/vents/bxchps-beeping-troubleshooting-noise.pdf][BXC^2 hps model]] (about the beeping).

* Exhaust Fan

The exhaust fan is made by Aereco also, a [[https://www.aereco.ie/products/exhaust-fans-ie/v4a-premium/][V4A336]] (The V4A Premium for 230V).

- [[file:/vents/TF4496_E_V4Apremium_display-4.pdf][Installation Guide]]
- [[file:/vents/FLY337GB_v4_display-4.pdf][Product Booklet]]
- [[file:/vents/TF4540_C_display-1.pdf][Replacement Kit Booklet]]


* Future Stuff
- There's a way to measure pressure using a manometer over these vents I believe, so that might be interesting to try in the future.
- I think the vents all make their way up to the attic, where there's a much larger exhaust, but I'm not completely sure on all the details on that yet.
  - At the same time, we also have a vent over the hob but that's venting a different way I think?
- I think these vents might also have features for Co2 but I'm not sure yet.
- The vent doors are adjustable I believe, so you can increase the amount of venting.
  - (This could be a trade-off of heat loss vs stagnant air I think, not explored yet).
- I haven't yet traced all the ducts around the place (starting with the exhaust).
